### ISSUE TITLE
repair layout

### ISSUE THREAD

**Issue by RoelofWobbenfrontend** [RoelofWobbenfrontend/tip-calculator-react#9]
I have to add the right classes so the buttons and so on are on the right place

**Comment by RoelofWobbenfrontend** [comment]
added the classes and submitted the changes.

Do you see any glitches ?

**Comment by RoelofWobbenfrontend** [comment]
@samjok  are you happy with the layout and inputs now.
Then we can figure out how to calculate things and display the outcome

**Comment by samjok** [comment]
I will check tomorrow. I think I will participate more at weekends. I code React projects also at work so I don't want to use too much of my free time to do the same. 😀

**Comment by RoelofWobbenfrontend** [comment]
Oke, as from tommorow iI will be offline till Monday/Tuesday because we are getting a new kitchen on 6 December and some people have to make some preprarations for it.

**Comment by samjok** [comment]
The layout is good. And everything is almost done. You have only small error there. Instead of props.tipPerPerson and props.totalPerPerson you need to have props.outcome.tipPerPerson and props.outcome.totalPerPerson. 

I found the bug by using React Developer Tools Chrome extension for debugging: https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi

**Comment by RoelofWobbenfrontend** [comment]
Thanks, 

and yes, it is almost done.
